# The following line imports the SLX logic that makes sure the individual
# command line tools are called as needed when issuing "make" commands in
# this folder or starting operations from within SLX IDE.
include $(SLX_HOME)/data/makefiles/seq/fpga.mk
# Please specify all project settings in "defines.mk".
